version: "3"

services:
  app:
    image: my-app:latest
    stdin_open: true
    tty: true
    build: .
    environment:
     - DISPLAY=${DISPLAY}
     - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /run/user:/run/user
    network_mode: host
